### ISSUE TITLE
EPOCH 1.0.7

### ISSUE THREAD

**Issue by GACI** [MigSDev5/Epoch_origins_pack#1]
Доброго времени суток!
Актуализируйте пожалуйста Epoch OriginsMod Pack под Epoch 1.0.7

**Comment by MigSDev5** [comment]
> Доброго времени суток!
> Актуализируйте пожалуйста Epoch OriginsMod Pack под Epoch 1.0.7

https://github.com/MigSDev5/Epoch-OriginsMod-Server-Package

**Comment by GACI** [comment]
Thank you!
And you can share Origins Mod 1.8.3 ?

**Comment by MigSDev5** [comment]
> Thank you!
> And you can share Origins Mod 1.8.3 ?

You can download Origins mod 1.0.3, via origins launcher:
[https://originsmod.info/download.html](url)

**Comment by GACI** [comment]
No results matched your search.

**Comment by MigSDev5** [comment]
https://originsmod.info/download.html

**Comment by GACI** [comment]
![Uploading Снимок.PNG…]()

**Comment by GACI** [comment]
Good day!
Install your Epoch-OriginsMod-Server Package.
But why is the Chernorus map loaded?
[ArmA2OA.zip](https://github.com/MigSDev5/Epoch_origins_pack/files/6720326/ArmA2OA.zip)

**Comment by GACI** [comment]
Good day!
In addition to the @OriginsMod mod, do you need to connect some other mod?

**Comment by MigSDev5** [comment]
Hello ! 
Yes @DayZ_Epoch
